### PR TITLE
New Metaboxes and extended Post Type

### PR DESCRIPTION
**Pull request by gsdefender**
Hi,
I have done several slight modifications to the framework: 
- Add Autocomplete Input, Multi Select, Constrained Number metabox views
- Extended PostType to allow map_meta_cap (I had to lockdown the WP backend for a project and show only the custom posts for some user types)

### CODE REVIEW

**Comment by theantichris** [comment]
Man, thanks! I'll review this as soon as I get a chance and merge it in. I really appreciate it.

**Comment by theantichris** [comment]
Sorry it has taken so long.

The field views look good. Why are you creating entirely new child classes rather than add the new functionality to the existing classes?

**Comment by gsdefender** [comment]
> Il giorno 30/mar/2016, alle ore 01:27, Christopher Lamm notifications@github.com ha scritto:
> 
> Sorry it has taken so long.
> 
> The field views look good. Why are you creating entirely new child classes rather than add the new functionality to the existing classes?

I know it is a poor justification, but as I was in a rush (really) for the project I needed these modifications for, I didn’t want to touch the original files.
Sorry :-|

**Comment by theantichris** [comment]
Well if you want to build the functionality into the main classes and have them as an option I'll merge it in with the main branch.

If you're fine with just using it as in we can close the PR.

**Comment by gsdefender** [comment]
> Il giorno 30/mar/2016, alle ore 14:08, Christopher Lamm notifications@github.com ha scritto:
> 
> Well if you want to build the functionality into the main classes and have them as an option I'll merge it in with the main branch.
> 
> If you're fine with just using it as in we can close the PR.

I think it would be worthwhile to have them merged. The most complex thing to merge IMHO is the custom post modification I have made.

**Pull request closed without merging**
